spring:
  security:
    user:
      name: user
      password: 1111

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081
